exam/accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view

app_name = 'accounts'

urlpatterns = [
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout')
]

exam/exam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls', 'accounts')),
    path('', include('webapp.urls', 'webapp')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam/webapp/urls.py
from django.urls import path
from webapp.views import ArticleListView, ArticleDetailView,\
    ArticleCreateView, ArticleUpdateView, ArticleDeleteView, UserListView, UserView, UserUpdateView

app_name = 'webapp'

urlpatterns = [
    path('', ArticleListView.as_view(), name='article_list'),
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article_detail'),
    path('article/<int:pk>', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>', ArticleDeleteView.as_view(), name='article_delete'),
    path('article/create', ArticleCreateView.as_view(), name='article_create'),
    path('users/', UserListView.as_view(), name='user_list'),
    path('users/<int:pk>', UserView.as_view(), name='user_office'),
    path('users/<int:pk>', UserUpdateView.as_view(), name='user_edit')

]

exam/accounts/models.py
from django.db import models

# Create your models here.

exam/webapp/models.py
from django.contrib.auth.models import User
from django.db import models

GENDER_CHOICES = [
    ['male', "Мужской"],
    ['female', "Женский"],
]

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, verbose_name="Пользователь")
    avatar = models.FileField(null=True, blank=True, verbose_name="Аватар")
    birth_date = models.DateField(null=True, blank=True, verbose_name="Дата рождения")
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default="male", verbose_name="Пол")
    phone_number = models.CharField(max_length=15, verbose_name="Номер телефона")
    friends = models.ManyToManyField(User, blank=True, related_name='friends', verbose_name='Друзья')

class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    text = models.TextField(max_length=10000, verbose_name='Текст')
    article_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='Посты', verbose_name='Автор')

exam/webapp/forms.py
from django import forms
from webapp.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['author']

exam/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout


def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('webapp:article_list')
        else:
            context['has_error'] = True
    return render(request, 'login_view.html', context=context)

def logout_view(request):
    logout(request)
    return redirect('webapp:article_list')

exam/webapp/views.py
from django.views.generic import DetailView, CreateView, UpdateView, View, DeleteView, ListView, TemplateView
from django.urls import reverse, reverse_lazy
from webapp.models import UserInfo, Post
from webapp.forms import PostForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render, get_object_or_404


class ArticleListView(ListView):
    model = Post
    template_name = 'article_list.html'

    def get_queryset(self):
        return super().get_queryset().order_by('-article_date')

class ArticleDetailView(DetailView):
    pass


class ArticleCreateView(CreateView):
    model = Post
    template_name = 'article_create.html'
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
        redirect('webapp:article_list')



class ArticleUpdateView(UpdateView):
    class PostUpdateView(LoginRequiredMixin, UpdateView):
        model = Post
        template_name = 'article_update.html'
        form_class = PostForm

    def get_success_url(self):
        return reverse('webapp:article_detail', kwargs={'pk': self.object.pk})

    def dispatch(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs['pk'])
        if self.request.user == post.author:
            return super(ArticleUpdateView, self).dispatch(request, *args, **kwargs)
        elif self.request.user.is_anonymous:
            return redirect('accounts:login')
        else:
            return redirect('webapp:article_detail', pk=kwargs['pk'])

class ArticleDeleteView(DeleteView):
    pass

class UserListView(ListView):
    model = UserInfo
    template_name = 'user_list.html'



class UserView(TemplateView, LoginRequiredMixin):
    template_name = "user_office.html"

    def dispatch(self, request, *args, **kwargs):
        if not UserInfo.objects.filter(user=request.user).exists():
            return redirect(reverse("edit_profile"))
        context = {
            'selected_user': request.user
        }
        return render(request, self.template_name, context)

class UserUpdateView(UpdateView):
    pass

exam/accounts/templates/login_view.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Вход</title>
</head>
<body>
<div class="container">
    <h1 class="text-center">Вход</h1>
    <form action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-text text-danger text-center">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-row form-group">
            <label for="username" class="col-2 form-text">Имя пользователя:</label>
            <input type="text" class="form-control col-10" name="username" id="username">
        </div>
        <div class="form-row form-group">
            <label for="password" class="col-2 form-text">Пароль:</label>
            <input type="password" class="form-control col-10" name="password" id="password">
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Войти</button>
        </div>
    </form>
</div>


    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

exam/webapp/templates/article_create.html
{% extends 'base.html' %}
{% block title %}Добавить статью{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    <form action="{% url 'webapp:article_create' %}" class="col-sm-3 text-left" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
    {% else %}
        {% url 'accounts:login' %}
    {% endif %}
{% endblock %}

exam/webapp/templates/article_detail.html
{% extends 'base.html' %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">{{ post.title }}</h1>
        <p class="lead">{{ post.text }}</p>
          <button type="button" class="btn btn-secondary"><a href="{% url 'webapp:user_office' user.pk %}">{{ post.author }}</a></button>
          <button type="button" class="btn btn-secondary"><a href="{% url 'webapp:article_update' post.pk %}">редактировать</a></button>
          <button class="btn btn-outline-light"><a href="{% url 'webapp:post_delete' post.pk %}" data-toggle="modal"
                                         data-target="#exampleModal{{ post.pk }}"><span
                    class="font-weight-bold">Удалить</span></a></button>
            <div class="modal fade" id="exampleModal{{ post.pk }}" tabindex="-1" role="dialog"
                 aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Вы уверены?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Вы уверены что хотите удалить пост?
                        </div>
                        <div class="modal-footer">
                            <a href="{% url 'webapp:article_delete' post.pk %}" class="btn btn-secondary">Да</a>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>
                        </div>
                    </div>
                </div>
            </div>
      </div>
    </div>
{% endblock %}

exam/webapp/templates/article_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Втентакли{% endblock %}
{% block content %}
   {% for post in post_list %}
    <div class="jumbotron">
      <h1 class="display-4"><a href="{% url 'webapp:article_detail' post.pk %}">{{ post.title }}</a></h1>
      <hr class="my-4">
      <p>{{ post.article_date }}</p>
{#      <a class="btn btn-primary btn-lg" href="{% url 'webapp:user_office' post.author.userinfopk %}" role="button">{{ post.author }}</a>#}
      <a class="btn btn-primary btn-lg" href="{% url 'webapp:article_update' post.pk %}" role="button">редактировать</a>
    </div>
    {% endfor %}
{% endblock %}

exam/webapp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Втентакли</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</body>
</html>

exam/webapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Втентакли{% endblock %}
{% block content %}
   {% for post in post_list %}
    <div class="jumbotron">
      <h1 class="display-4">{{ post.title }}</h1>
      <p class="lead">{{ post.text }}</p>
      <hr class="my-4">
      <p>{{ post.article_date }}</p>
      <a class="btn btn-primary btn-lg" href="#" role="button">{{ post.author }}</a>
    </div>
    {% endfor %}
{% endblock %}

exam/webapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light justify-content-between" style="background-color: #9fcdff;">
    <a class="navbar-brand" href="{% url 'webapp:article_list' %}">Втентакли</a>
    <li class="nav-item"><a href="{% url 'webapp:user_list' %}" class="nav-link">Список пользователей</a></li>
    {% if user.is_authenticated %}
        <li class="nav-item"><a href="{% url 'webapp:article_create' %}" class="nav-link">Добавить статью</a></li>
        <li class="nav-item navbar-text">Привет, <a href="{% url 'webapp:user_office' user.pk %}">{{ user.username }}</a>!</li>
        <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link">Выход</a></li>
        {% block menu %}{% endblock %}
    {% else %}
        <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link">Вход</a></li>
    {% endif %}
</nav>

exam/webapp/templates/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Втентакли{% endblock %}
{% block content %}
   {% for post in post_list %}
    <div class="jumbotron">
      <h1 class="display-4">{{ post.title }}</h1>
      <p class="lead">{{ post.text }}</p>
      <hr class="my-4">
      <p>{{ post.article_date }}</p>
      <a class="btn btn-primary btn-lg" href="#" role="button">{{ post.author }}</a>
    </div>
    {% endfor %}
{% endblock %}

exam/webapp/templates/user_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Пользователи{% endblock %}
{% block content %}
    <div class="list-group">
      <a href="#" class="list-group-item list-group-item-action active">
        Пользователи
      </a>
        {% for i in userinfo_list %}
            <div class="jumbotron">
              <h1 class="display-4">{{ user.userinfo }}</h1>
              <p class="lead">{{ user.birth_date }}</p>
              <hr class="my-4">
              <p>{{ user.phone_number }}</p>
              <a class="btn btn-primary btn-lg" href="{% url 'webapp:user_office' user.pk %}" role="button">{{ user.user }}</a>
            </div>
      {% endfor %}
    </div>
{% endblock %}

exam/webapp/templates/user_office.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container content">
        <div class="row" style="margin-left: 20px;">
            <div class="col5">
                {% if selected_user.userinfo.avatar %}
                    <img src="{{ selected_user.avatar.url }}" class="avatar-img img-thumbnail" style="width: 15rem;, height: 15rem;">
                {% else %}
                    <img src="{% static 'img/user.jpg' %}" class="avatar-img img-thumbnail">
                {% endif %}
                <br>
                <br>
                {% if selected_user.id == user.id %}
                    <a href="{% url 'webapp:user_edit' user.pk %}" class="btn btn-sm btn-info">Редактировать профиль</a>
                {% endif %}
            </div>
            <div class="col">
                <dl class="row">
                    <dt class="col-sm-3 text-right">Логин</dt>
                    <dd class="col-sm-9">{{ selected_user }}</dd>

                    <dt class="col-sm-3 text-right">Дата рождения</dt>
                    <dd class="col-sm-9">{{ selected_user.userinfo.birth_date|date:"d M Y" }}</dd>

                    <dt class="col-sm-3 text-right">Пол</dt>
                    <dd class="col-sm-9">{{ selected_user.userinfo.gender }}</dd>

                    <dt class="col-sm-3 text-right">Друзья</dt>
                        {% for user_friend in selected_user.friends.all %}
                            <dd class="col-sm-9">{{ user_friend.user }}</dd>
                    {% endfor %}

                </dl>
            </div>
        </div>

    </div>
{% endblock %}